Get selection of makerspaces
julian-code/makersofdenmark pull request #51
Opened 2020-10-23 17:41 UTC by mnabe

2020-10-23 17:44 UTC, mnabe commented
Jeg får en fejl på sidste linje i min test, som automatisk går til Dispose(); 

Fejlen: "System.InvalidOperationException : Sequence contains no elements"

Jeg kigger selvfølgelig videre på det selv, men har oprettet et pull request i tilfælde af at I kan spotte fejlen

2020-10-24 12:31 UTC, jesp209i commented on src/MakersOfDenmark.Application/Queries/V1/GetSelectionOfMakerSpaces.cs
> +            var makerSpace = await _context.MakerSpace.AsNoTracking().FirstAsync(x => x.Name == request.Name);
På linje 36 mangler du at include Address. Som du gør det nu, så henter den ikke Addressen med ud. 
Se mit eksempel nedenfor :)
```
await _context.MakerSpace
          .Include(x=>x.Address)
          .AsNoTracking()
          .FirstAsync(x => x.Name == request.Name);
```

2020-10-24 13:50 UTC, mnabe commented on src/MakersOfDenmark.Application/Queries/V1/GetSelectionOfMakerSpaces.cs
> +            var makerSpace = await _context.MakerSpace.AsNoTracking().FirstAsync(x => x.Name == request.Name);
Du havde helt ret. Mange tak!

2020-10-24 14:00 UTC, mnabe commented
Jeg havde et problem med en test, som Jesper hjalp mig med - tak for det! 

I øjeblikket søger den kun på og returnerer ét MakerSpace, da jeg syntes det gav mest mening i første omgang - men det kan være, at flere MakerSpaces har samme navn og at det vil være mere hensigtsmæssigt at returnerer en liste. Men helt generelt kommer jeg nok til at refaktorere.

Jeg venter med at lege med FluentValidation til at dette er merget til master, da jeg så kan branche ud fra masteren, hvor FluentValidation allerede er installeret 🙂

2020-10-24 17:06 UTC, julian-code commented
@mnabe er den stadig en WIP? :)

2020-10-24 19:16 UTC, julian-code requested changes

2020-10-24 19:16 UTC, julian-code commented on src/MakersOfDenmark.Application/Queries/V1/GetSelectionOfMakerSpaces.cs
> +        public string Id { get; set; }
Der er faktisk ingen grund til at kalde ToString(). Serializeringen der alligevel sker af System.Text.Json gør det for dig når den returnere via. API'et.

Så for at have en mere sigende kode kan du blot bruge Guid på linje 51.

2020-10-24 19:16 UTC, julian-code commented on src/MakersOfDenmark.Application/Queries/V1/GetSelectionOfMakerSpaces.cs
> +            var makerSpace = await _context.MakerSpace.Include(x => x.Address).AsNoTracking().FirstAsync(x => x.Name == request.Name);
God brug af AsNoTracking(). Det gør din query mere performant, hvis du altså ikke skal lave nogle ændringer.

2020-10-24 19:16 UTC, julian-code commented on src/MakersOfDenmark.Application/Queries/V1/GetSelectionOfMakerSpaces.cs
> +            var makerSpace = await _context.MakerSpace.Include(x => x.Address).AsNoTracking().FirstAsync(x => x.Name == request.Name);
Når man bruger FirstAsync skal man passe på - hvis den ikke finder noget i listen, så thrower den en exception.

Ved brug af FirstOrDefaultAsync() er det i stedet default værdien af MakerSpace der bliver returneret, hvis intet kan findes, hvilket i dette tilfælde er null

https://stackoverflow.com/questions/1024559/when-to-use-first-and-when-to-use-firstordefault-with-linq

2020-10-24 19:16 UTC, julian-code commented on tests/MakersOfDenmark.WebAPI.Tests/GetSelectionOfMakerSpacesTest.cs
> +        {
Hvad hvis din handler ikke finder noget MakerSpace med det navn? :)

2020-10-25 10:20 UTC, mnabe commented
@julian-code Tak for nogle rigtig gode kommentarer, som var meget brugbare! Jeg har prøvet at efterkomme dem.

2020-10-25 11:04 UTC, julian-code approved these changes

2020-10-25 11:04 UTC, merged